// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package commit

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Path      *string `mapstructure:"path" cty:"path" hcl:"path"`
	CommitIsh *string `mapstructure:"commit_ish" cty:"commit_ish" hcl:"commit_ish"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"path":       &hcldec.AttrSpec{Name: "path", Type: cty.String, Required: false},
		"commit_ish": &hcldec.AttrSpec{Name: "commit_ish", Type: cty.String, Required: false},
	}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
	Hash         *string  `mapstructure:"hash" cty:"hash" hcl:"hash"`
	Branch       *string  `mapstructure:"branch" cty:"branch" hcl:"branch"`
	Author       *string  `mapstructure:"author" cty:"author" hcl:"author"`
	Committer    *string  `mapstructure:"committer" cty:"committer" hcl:"committer"`
	PGPSignature *string  `mapstructure:"pgp_signature" cty:"pgp_signature" hcl:"pgp_signature"`
	Message      *string  `mapstructure:"message" cty:"message" hcl:"message"`
	TreeHash     *string  `mapstructure:"tree_hash" cty:"tree_hash" hcl:"tree_hash"`
	ParentHashes []string `mapstructure:"parent_hashes" cty:"parent_hashes" hcl:"parent_hashes"`
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"hash":          &hcldec.AttrSpec{Name: "hash", Type: cty.String, Required: false},
		"branch":        &hcldec.AttrSpec{Name: "branch", Type: cty.String, Required: false},
		"author":        &hcldec.AttrSpec{Name: "author", Type: cty.String, Required: false},
		"committer":     &hcldec.AttrSpec{Name: "committer", Type: cty.String, Required: false},
		"pgp_signature": &hcldec.AttrSpec{Name: "pgp_signature", Type: cty.String, Required: false},
		"message":       &hcldec.AttrSpec{Name: "message", Type: cty.String, Required: false},
		"tree_hash":     &hcldec.AttrSpec{Name: "tree_hash", Type: cty.String, Required: false},
		"parent_hashes": &hcldec.AttrSpec{Name: "parent_hashes", Type: cty.List(cty.String), Required: false},
	}
	return s
}
