name: Ensure Docs are Compiled
on:
  push:
jobs:
  ensure-docs-compiled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      - shell: bash
        run: make generate
      - shell: bash
        run: |
          if [[ -z "$(git status -s)" ]]; then
            echo "OK"
          else
            echo "Docs have been updated, but the compiled docs have not been committed."
            echo "Run 'make generate and commit the result to resolve this error."
            exit 1
          fi

